CREATE TABLE MOVIES 
(
MOVIE_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),  
MOVIE_TITLE VARCHAR(100) NOT NULL,
RELEASE_DATE DATE NOT NULL,
PRICE MONEY NOT NULL,
RATING DECIMAL(5,2) NOT NULL,
GENRE VARCHAR(20)
)

CREATE TABLE ORDERS
(
ORDER_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
RENTAL_DATE DATE NOT NULL,
RETURN_DATE DATE NOT NULL,
MOVIE_ID INT FOREIGN KEY REFERENCES MOVIES(MOVIE_ID),
NET_AMOUNT MONEY NOT NULL,
DISCOUNT DECIMAL(5,2),
GROSS_AMOUNT MONEY NOT NULL,
)

